// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calcite/v1/calcite_rewriter.proto
// Manually maintained — regenerate with: buf generate

package calcitepb

// Decision mirrors the PDP BulkDecideResponse per-resource decision.
// Passed to the Calcite sidecar so it can apply row filters and column masks.
type Decision struct {
	ResourceType  string            `json:"resource_type"`
	ResourceName  string            `json:"resource_name"`
	Effect        string            `json:"effect"` // "ALLOW" | "DENY"
	RowFilter     string            `json:"row_filter,omitempty"`
	AllowedCols   []string          `json:"allowed_columns,omitempty"`
	MaskedCols    map[string]string `json:"masked_columns,omitempty"` // col → mask_fn name
	MaxRows       int64             `json:"max_rows,omitempty"`
	DecisionHash  string            `json:"decision_hash,omitempty"`
}

// CatalogTable describes a table in the datasource catalog snapshot.
type CatalogTable struct {
	Schema  string   `json:"schema"`
	Table   string   `json:"table"`
	Columns []string `json:"columns"`
}

// RewriteRequest is sent by the proxy to the Calcite sidecar.
type RewriteRequest struct {
	RawSQL        string            `json:"raw_sql"`
	SourceDialect string            `json:"source_dialect"` // always "postgres"
	TargetDialect string            `json:"target_dialect"` // always "postgres"
	Decisions     []*Decision       `json:"decisions"`
	Catalog       []*CatalogTable   `json:"catalog"`
	Binds         map[string]string `json:"binds,omitempty"`
	TenantID      string            `json:"tenant_id"`
	UserID        string            `json:"user_id"`
	RequestID     string            `json:"request_id"`
}

// RewriteResponse is returned by the Calcite sidecar.
type RewriteResponse struct {
	RewrittenSQL       string   `json:"rewritten_sql"`
	ReferencedTables   []string `json:"referenced_tables"`
	ReferencedColumns  []string `json:"referenced_columns"`
	ASTHash            string   `json:"ast_hash"`
	RewriteDurationMs  int64    `json:"rewrite_duration_ms"`
	Error              *RewriteError `json:"error,omitempty"`
}

// RewriteError carries structured error information.
type RewriteError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (r *RewriteResponse) HasError() bool {
	return r.Error != nil && r.Error.Code != ""
}
