// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: calcite/v1/calcite_rewriter.proto
// Manually maintained — regenerate with: buf generate

package calcitepb

import (
	"context"
	"encoding/json"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const CalciteRewriter_Rewrite_FullMethodName = "/calcite.v1.CalciteRewriter/Rewrite"

// CalciteRewriterClient is the client API for CalciteRewriter service.
type CalciteRewriterClient interface {
	Rewrite(ctx context.Context, in *RewriteRequest, opts ...grpc.CallOption) (*RewriteResponse, error)
}

type calciteRewriterClient struct {
	cc grpc.ClientConnInterface
}

func NewCalciteRewriterClient(cc grpc.ClientConnInterface) CalciteRewriterClient {
	return &calciteRewriterClient{cc}
}

func (c *calciteRewriterClient) Rewrite(ctx context.Context, in *RewriteRequest, opts ...grpc.CallOption) (*RewriteResponse, error) {
	// Use JSON encoding over gRPC for simplicity (matches Spring Boot grpc-json transcoding).
	// In production, switch to protobuf binary encoding.
	payload, err := json.Marshal(in)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "marshal request: %v", err)
	}

	var raw []byte
	err = c.cc.Invoke(ctx, CalciteRewriter_Rewrite_FullMethodName,
		&jsonRawMsg{payload}, &jsonRawMsg{raw}, opts...)
	if err != nil {
		return nil, err
	}

	out := new(RewriteResponse)
	if err := json.Unmarshal(raw, out); err != nil {
		return nil, status.Errorf(codes.Internal, "unmarshal response: %v", err)
	}
	return out, nil
}

// jsonRawMsg wraps raw JSON bytes to satisfy grpc codec requirements.
type jsonRawMsg struct {
	data []byte
}

func (j *jsonRawMsg) ProtoMessage()             {}
func (j *jsonRawMsg) Reset()                    { j.data = nil }
func (j *jsonRawMsg) String() string            { return string(j.data) }
func (j *jsonRawMsg) Marshal() ([]byte, error)  { return j.data, nil }
func (j *jsonRawMsg) Unmarshal(b []byte) error  { j.data = b; return nil }
