apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "region-router.fullname" . }}
  labels:
    {{- include "region-router.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "region-router.selectorLabels" . | nindent 6 }}
