// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pdp/v1/pdp.proto

package pdpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect int32

const (
	Effect_EFFECT_UNSPECIFIED Effect = 0
	Effect_EFFECT_PERMIT      Effect = 1
	Effect_EFFECT_DENY        Effect = 2
)

var (
	Effect_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "EFFECT_PERMIT",
		2: "EFFECT_DENY",
	}
	Effect_value = map[string]int32{
		"EFFECT_UNSPECIFIED": 0,
		"EFFECT_PERMIT":      1,
		"EFFECT_DENY":        2,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}
func (x Effect) String() string              { return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x)) }
func (Effect) Descriptor() protoreflect.EnumDescriptor { return nil } // stub
func (Effect) Type() protoreflect.EnumType              { return nil } // stub
func (x Effect) Number() protoreflect.EnumNumber        { return protoreflect.EnumNumber(x) }

// DecideRequest carries the serialised + HMAC-signed SessionContext.
type DecideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubjectSessionContext []byte            `protobuf:"bytes,1,opt,name=subject_session_context,json=subjectSessionContext,proto3" json:"subject_session_context,omitempty"`
	SubjectSessionSig     []byte            `protobuf:"bytes,2,opt,name=subject_session_sig,json=subjectSessionSig,proto3" json:"subject_session_sig,omitempty"`
	SubjectSessionKeyId   string            `protobuf:"bytes,3,opt,name=subject_session_key_id,json=subjectSessionKeyId,proto3" json:"subject_session_key_id,omitempty"`
	Action                string            `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Resource              string            `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	DataSourceId          string            `protobuf:"bytes,6,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	Context               map[string]string `protobuf:"bytes,7,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IdempotencyKey        string            `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
}

func (x *DecideRequest) Reset()         { *x = DecideRequest{} }
func (x *DecideRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DecideRequest) ProtoMessage()    {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	return nil // stub — use JSON codec in tests; real proto reflection requires generated file descriptors
}

func (x *DecideRequest) GetSubjectSessionContext() []byte {
	if x != nil {
		return x.SubjectSessionContext
	}
	return nil
}
func (x *DecideRequest) GetSubjectSessionSig() []byte {
	if x != nil {
		return x.SubjectSessionSig
	}
	return nil
}
func (x *DecideRequest) GetSubjectSessionKeyId() string {
	if x != nil {
		return x.SubjectSessionKeyId
	}
	return ""
}
func (x *DecideRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}
func (x *DecideRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}
func (x *DecideRequest) GetDataSourceId() string {
	if x != nil {
		return x.DataSourceId
	}
	return ""
}
func (x *DecideRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}
func (x *DecideRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// RowFilter carries the dialect-neutral predicate AST as compact JSON.
type RowFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AstJson []byte `protobuf:"bytes,1,opt,name=ast_json,json=astJson,proto3" json:"ast_json,omitempty"`
}

func (x *RowFilter) Reset()         { *x = RowFilter{} }
func (x *RowFilter) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RowFilter) ProtoMessage()    {}
func (x *RowFilter) ProtoReflect() protoreflect.Message { return nil }
func (x *RowFilter) GetAstJson() []byte {
	if x != nil {
		return x.AstJson
	}
	return nil
}

type Obligation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Params map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Obligation) Reset()         { *x = Obligation{} }
func (x *Obligation) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Obligation) ProtoMessage()    {}
func (x *Obligation) ProtoReflect() protoreflect.Message { return nil }
func (x *Obligation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *Obligation) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Effect           Effect            `protobuf:"varint,1,opt,name=effect,proto3,enum=pdp.v1.Effect" json:"effect,omitempty"`
	AllowedColumns   []string          `protobuf:"bytes,2,rep,name=allowed_columns,json=allowedColumns,proto3" json:"allowed_columns,omitempty"`
	DeniedColumns    []string          `protobuf:"bytes,3,rep,name=denied_columns,json=deniedColumns,proto3" json:"denied_columns,omitempty"`
	ColumnMasks      map[string]string `protobuf:"bytes,4,rep,name=column_masks,json=columnMasks,proto3" json:"column_masks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RowFilter        *RowFilter        `protobuf:"bytes,5,opt,name=row_filter,json=rowFilter,proto3" json:"row_filter,omitempty"`
	Obligations      []*Obligation     `protobuf:"bytes,6,rep,name=obligations,proto3" json:"obligations,omitempty"`
	Reason           string            `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicySetVersion string            `protobuf:"bytes,8,opt,name=policy_set_version,json=policySetVersion,proto3" json:"policy_set_version,omitempty"`
	TtlSeconds       int32             `protobuf:"varint,9,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	MatchedPolicyIds []string          `protobuf:"bytes,10,rep,name=matched_policy_ids,json=matchedPolicyIds,proto3" json:"matched_policy_ids,omitempty"`
}

func (x *Decision) Reset()         { *x = Decision{} }
func (x *Decision) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Decision) ProtoMessage()    {}
func (x *Decision) ProtoReflect() protoreflect.Message { return nil }

func (x *Decision) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}
func (x *Decision) GetAllowedColumns() []string {
	if x != nil {
		return x.AllowedColumns
	}
	return nil
}
func (x *Decision) GetDeniedColumns() []string {
	if x != nil {
		return x.DeniedColumns
	}
	return nil
}
func (x *Decision) GetColumnMasks() map[string]string {
	if x != nil {
		return x.ColumnMasks
	}
	return nil
}
func (x *Decision) GetRowFilter() *RowFilter {
	if x != nil {
		return x.RowFilter
	}
	return nil
}
func (x *Decision) GetObligations() []*Obligation {
	if x != nil {
		return x.Obligations
	}
	return nil
}
func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}
func (x *Decision) GetPolicySetVersion() string {
	if x != nil {
		return x.PolicySetVersion
	}
	return ""
}
func (x *Decision) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}
func (x *Decision) GetMatchedPolicyIds() []string {
	if x != nil {
		return x.MatchedPolicyIds
	}
	return nil
}

type BulkDecideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*DecideRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *BulkDecideRequest) Reset()         { *x = BulkDecideRequest{} }
func (x *BulkDecideRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*BulkDecideRequest) ProtoMessage()    {}
func (x *BulkDecideRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *BulkDecideRequest) GetRequests() []*DecideRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BulkDecideItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *DecideRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Decision *Decision      `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	Error    string         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BulkDecideItem) Reset()         { *x = BulkDecideItem{} }
func (x *BulkDecideItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (*BulkDecideItem) ProtoMessage()    {}
func (x *BulkDecideItem) ProtoReflect() protoreflect.Message { return nil }
func (x *BulkDecideItem) GetRequest() *DecideRequest {
	if x != nil {
		return x.Request
	}
	return nil
}
func (x *BulkDecideItem) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}
func (x *BulkDecideItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BulkDecideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*BulkDecideItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BulkDecideResponse) Reset()         { *x = BulkDecideResponse{} }
func (x *BulkDecideResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*BulkDecideResponse) ProtoMessage()    {}
func (x *BulkDecideResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *BulkDecideResponse) GetItems() []*BulkDecideItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DecisionExplanation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decision        *Decision `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	MatchedRuleIds  []string  `protobuf:"bytes,2,rep,name=matched_rule_ids,json=matchedRuleIds,proto3" json:"matched_rule_ids,omitempty"`
	HumanReadable   string    `protobuf:"bytes,3,opt,name=human_readable,json=humanReadable,proto3" json:"human_readable,omitempty"`
	EvaluationTrace []string  `protobuf:"bytes,4,rep,name=evaluation_trace,json=evaluationTrace,proto3" json:"evaluation_trace,omitempty"`
}

func (x *DecisionExplanation) Reset()         { *x = DecisionExplanation{} }
func (x *DecisionExplanation) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DecisionExplanation) ProtoMessage()    {}
func (x *DecisionExplanation) ProtoReflect() protoreflect.Message { return nil }
func (x *DecisionExplanation) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}
func (x *DecisionExplanation) GetMatchedRuleIds() []string {
	if x != nil {
		return x.MatchedRuleIds
	}
	return nil
}
func (x *DecisionExplanation) GetHumanReadable() string {
	if x != nil {
		return x.HumanReadable
	}
	return ""
}
func (x *DecisionExplanation) GetEvaluationTrace() []string {
	if x != nil {
		return x.EvaluationTrace
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId   string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Conditions []byte `protobuf:"bytes,2,opt,name=conditions,proto3" json:"conditions,omitempty"`
}

func (x *ValidateRequest) Reset()         { *x = ValidateRequest{} }
func (x *ValidateRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ValidateRequest) ProtoMessage()    {}
func (x *ValidateRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ValidateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}
func (x *ValidateRequest) GetConditions() []byte {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid   bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors  []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ValidateResponse) Reset()         { *x = ValidateResponse{} }
func (x *ValidateResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ValidateResponse) ProtoMessage()    {}
func (x *ValidateResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}
func (x *ValidateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// ensure unused imports are referenced
var _ = reflect.TypeOf
var _ = sync.Once{}
