// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: pdp/v1/pdp.proto

package pdpv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// PDPClient is the client API for PDP service.
type PDPClient interface {
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*Decision, error)
	BulkDecide(ctx context.Context, in *BulkDecideRequest, opts ...grpc.CallOption) (*BulkDecideResponse, error)
	Explain(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecisionExplanation, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type pDPClient struct {
	cc grpc.ClientConnInterface
}

func NewPDPClient(cc grpc.ClientConnInterface) PDPClient {
	return &pDPClient{cc}
}

func (c *pDPClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*Decision, error) {
	out := new(Decision)
	err := c.cc.Invoke(ctx, PDP_Decide_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDPClient) BulkDecide(ctx context.Context, in *BulkDecideRequest, opts ...grpc.CallOption) (*BulkDecideResponse, error) {
	out := new(BulkDecideResponse)
	err := c.cc.Invoke(ctx, PDP_BulkDecide_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDPClient) Explain(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecisionExplanation, error) {
	out := new(DecisionExplanation)
	err := c.cc.Invoke(ctx, PDP_Explain_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDPClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, PDP_Validate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDPServer is the server API for PDP service.
// All implementations must embed UnimplementedPDPServer for forward compatibility.
type PDPServer interface {
	Decide(context.Context, *DecideRequest) (*Decision, error)
	BulkDecide(context.Context, *BulkDecideRequest) (*BulkDecideResponse, error)
	Explain(context.Context, *DecideRequest) (*DecisionExplanation, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedPDPServer()
}

// UnimplementedPDPServer must be embedded to have forward compatible implementations.
type UnimplementedPDPServer struct{}

func (UnimplementedPDPServer) Decide(context.Context, *DecideRequest) (*Decision, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedPDPServer) BulkDecide(context.Context, *BulkDecideRequest) (*BulkDecideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkDecide not implemented")
}
func (UnimplementedPDPServer) Explain(context.Context, *DecideRequest) (*DecisionExplanation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedPDPServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedPDPServer) mustEmbedUnimplementedPDPServer() {}

// UnsafePDPServer may be embedded to opt out of forward compatibility for this service.
type UnsafePDPServer interface {
	mustEmbedUnimplementedPDPServer()
}

const (
	PDP_Decide_FullMethodName      = "/pdp.v1.PDP/Decide"
	PDP_BulkDecide_FullMethodName  = "/pdp.v1.PDP/BulkDecide"
	PDP_Explain_FullMethodName     = "/pdp.v1.PDP/Explain"
	PDP_Validate_FullMethodName    = "/pdp.v1.PDP/Validate"
)

func RegisterPDPServer(s grpc.ServiceRegistrar, srv PDPServer) {
	s.RegisterService(&PDP_ServiceDesc, srv)
}

func _PDP_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDPServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDP_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDPServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDP_BulkDecide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkDecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDPServer).BulkDecide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDP_BulkDecide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDPServer).BulkDecide(ctx, req.(*BulkDecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDP_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDPServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDP_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDPServer).Explain(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDP_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDPServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDP_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDPServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PDP_ServiceDesc is the grpc.ServiceDesc for PDP service.
var PDP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdp.v1.PDP",
	HandlerType: (*PDPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decide",
			Handler:    _PDP_Decide_Handler,
		},
		{
			MethodName: "BulkDecide",
			Handler:    _PDP_BulkDecide_Handler,
		},
		{
			MethodName: "Explain",
			Handler:    _PDP_Explain_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _PDP_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pdp/v1/pdp.proto",
}
