apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "compliance-service.fullname" . }}
  labels:
    {{- include "compliance-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "compliance-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "compliance-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "compliance-service.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: compliance-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- if .Values.otel.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.endpoint }}
            {{- end }}
            {{- range $key, $ref := .Values.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $ref.secretName }}
                  key: {{ $ref.key }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
